name: eCTS Mabl Tests

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 12 * * *'  # Runs at 12 PM UTC every day
    - cron: '0 14 * * *'  # Runs at 2 PM UTC every day
    - cron: '30 17 * * *'  # Runs at 5:30 PM UTC every day
    - cron: '0 18 * * *'  # Runs at 6 PM UTC every day

jobs:
  test:
    name: mabl Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Regression Tests
        id: mabl-test-deployment
        uses: mablhq/github-run-tests-action@v1
        env:
          MABL_API_KEY: ${{ secrets.MABL_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.MABL_GITHUB_TOKEN }}
        with:
          application-id: ${{ secrets.APPLICATION_ID }}
          environment-id: ${{ secrets.ENVIRONMENT_ID }}
          plan-labels: TEH-eCTS-Regression
          mabl-branch: master
          browser-types: |
            chrome
